FROM node:18 AS builder
WORKDIR /app

# Accept build args
ARG VITE_ENVIRONMENT=development
ARG VITE_BACKEND_URL_PRODUCTION
ARG VITE_BACKEND_URL_STAGING
ARG VITE_BACKEND_URL_DEVELOPMENT

# Set environment variables so Vite can read them
ENV VITE_ENVIRONMENT=$VITE_ENVIRONMENT
ENV VITE_BACKEND_URL_PRODUCTION=$VITE_BACKEND_URL_PRODUCTION
ENV VITE_BACKEND_URL_STAGING=$VITE_BACKEND_URL_STAGING
ENV VITE_BACKEND_URL_DEVELOPMENT=$VITE_BACKEND_URL_DEVELOPMENT

COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
