name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - production
      - staging

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout specific commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push production image
        if: github.ref_name == 'production'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tjcbento/penalty-frontend:production-${{ github.sha }}
          build-args: |
            VITE_ENVIRONMENT=production

      - name: Build and push staging image
        if: github.ref_name == 'staging'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tjcbento/penalty-frontend:staging-${{ github.sha }}
          build-args: |
            VITE_ENVIRONMENT=staging
