name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - production
      - staging

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tag based on branch
        id: vars
        run: |
          if [[ "${{ github.ref_name }}" == "production" ]]; then
            echo "TAG=production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "TAG=staging" >> $GITHUB_OUTPUT
          else
            echo "Unsupported branch"
            exit 1
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tjcbento/penalty-frontend:${{ steps.vars.outputs.TAG }}
