name: Build and Push Frontend Docker Images

on:
  push:
    branches:
      - main
      - production
      - staging
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push production image if on main or production branch
      - name: Build and push production image
        if: github.ref_name == 'production' || github.ref_name == 'main'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tjcbento/penalty-frontend:production
          build-args: |
            VITE_ENVIRONMENT=production

      # Build and push staging image if on main or staging branch
      - name: Build and push staging image
        if: github.ref_name == 'staging' || github.ref_name == 'main'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tjcbento/penalty-frontend:staging
          build-args: |
            VITE_ENVIRONMENT=staging
