name: Build and Push Frontend Docker Images

on:
  push:
    branches:
      - production
      - staging
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push production image
        if: github.ref_name == 'production'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tjcbento/penalty-frontend:production
          build-args: |
            VITE_ENVIRONMENT=production
            VITE_BACKEND_URL_PRODUCTION=https://api.penalty.bet
            VITE_BACKEND_URL_STAGING=https://api.penalty.bet
            VITE_BACKEND_URL_DEVELOPMENT=http://localhost:3000

      - name: Build and push staging image
        if: github.ref_name == 'staging'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tjcbento/penalty-frontend:staging
          build-args: |
            VITE_ENVIRONMENT=staging
            VITE_BACKEND_URL_PRODUCTION=https://api.penalty.bet
            VITE_BACKEND_URL_STAGING=https://api.penalty.bet
            VITE_BACKEND_URL_DEVELOPMENT=http://localhost:3000
